#:schema https://raw.githubusercontent.com/cloudflare/wrangler2/main/packages/wrangler/config-schema.json
name = "daily-project"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-04-01"
compatibility_flags = [ "nodejs_compat" ]
